/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.SupermercadoCorreia.Estoque.Forms;

import br.SupermercadoCorreia.Estoque.Bean.Product;
import br.SupermercadoCorreia.Estoque.DAO.ProductDAO;
import br.SupermercadoCorreia.Estoque.JDialogs.RefreshProducts_JD;
import funcoes.CDbl;
import funcoes.RobotJCR;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ExchangeJF extends javax.swing.JFrame {

    List<Product> products_exchange;
    List<Product> products;

    /**
     * Creates new form ExchangeJF
     */
    public ExchangeJF() {
        initComponents();
        new RefreshProducts_JD(null, true).setVisible(true);
        products_exchange = new ProductDAO().findAll_Type_Use(ProductDAO.EXCHANGE_TABLE);
        products = new ProductDAO().findAll();
        for (Product p : products_exchange) {
            for (Product pp : products) {
                if (pp.getCode().equals(p.getCode())) {
                    p.setProvider(pp.getProvider());
                }
            }
        }

        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_desc = new javax.swing.JTextField();
        txt_prov = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_robot = new javax.swing.JButton();
        lbl_total = new javax.swing.JLabel();
        lbl_linhas = new javax.swing.JLabel();
        btn_removeExchange = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        delay = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Fornecedor", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(120);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(130);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(180);
            jTable1.getColumnModel().getColumn(3).setMinWidth(60);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        txt_desc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_descKeyPressed(evt);
            }
        });

        txt_prov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_provKeyPressed(evt);
            }
        });

        jLabel1.setText("Descrição");

        jLabel2.setText("Fornecedor");

        btn_robot.setText("Iniciar Robo");
        btn_robot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_robotActionPerformed(evt);
            }
        });

        lbl_total.setText("Total:");

        lbl_linhas.setText("Linhas:");

        btn_removeExchange.setText("Retirar das Trocas");
        btn_removeExchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeExchangeActionPerformed(evt);
            }
        });

        jLabel3.setText("Delay Padrão");

        delay.setModel(new javax.swing.SpinnerNumberModel(50, 0, 200, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txt_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_linhas, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(delay, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_removeExchange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_robot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_total)
                            .addComponent(lbl_linhas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(btn_robot))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(delay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_removeExchange)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_descKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descKeyPressed
        preencherTabela();
    }//GEN-LAST:event_txt_descKeyPressed

    private void txt_provKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_provKeyPressed
        preencherTabela();
    }//GEN-LAST:event_txt_provKeyPressed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            if (jTable1.getSelectedRow() >= 0) {
                DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
                tb.removeRow(jTable1.getSelectedRow());
            }
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void btn_robotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_robotActionPerformed
        new Thread(() -> {
            try {
                RobotJCR.AltTab(50);
                Thread.sleep(2000);
                for (int x = 0; x < jTable1.getRowCount(); x++) {
                    try {
                        String codigo = getCodeSelected(x);
                        String un = "UN";
                        String valor = "1";
                        for (Product p : products) {
                            if (p.getCode().equals(codigo)) {
                                un = p.getUnity();
                                double v = p.getCost_value();
                                if (v == 0) {
                                    v = 1;
                                }
                                valor = Double.toString(CDbl.CDblDuasCasas(v));
                                break;
                            }
                        }
                        String quantidade = getAmountSelected(x, un);
                        if (!quantidade.equals("0")) {
                            RobotJCR.executar(codigo, (int) delay.getValue());
                            RobotJCR.executar(KeyEvent.VK_ENTER, (int) delay.getValue());

                            RobotJCR.executar(quantidade, (int) delay.getValue());
                            RobotJCR.executar(KeyEvent.VK_ENTER, (int) delay.getValue());

                            RobotJCR.executar(valor, (int) delay.getValue());
                            RobotJCR.executar(KeyEvent.VK_ENTER, (int) delay.getValue());

                        }
                    } catch (Exception e) {
                        System.err.println(e);
                    }
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(ExchangeJF.class.getName()).log(Level.SEVERE, null, ex);
            }
            btn_removeExchange.setEnabled(true);
        }).start();
    }//GEN-LAST:event_btn_robotActionPerformed

    private void btn_removeExchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeExchangeActionPerformed
        for (int x = 0; x < jTable1.getRowCount(); x++) {
            long code = Long.parseLong((String) jTable1.getValueAt(x, 0));
            if (!new ProductDAO().setAmount_type_use(code, 0, ProductDAO.EXCHANGE_TABLE)) {
                JOptionPane.showMessageDialog(null, "Problema ao tentar dar baixa no banco de dados.");
            }
        }
        products_exchange = new ProductDAO().findAll_Type_Use(ProductDAO.EXCHANGE_TABLE);
        products = new ProductDAO().findAll();
        for (Product p : products_exchange) {
            for (Product pp : products) {
                if (pp.getCode().equals(p.getCode())) {
                    p.setProvider(pp.getProvider());
                }
            }
        }

        preencherTabela();
    }//GEN-LAST:event_btn_removeExchangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExchangeJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExchangeJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExchangeJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExchangeJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExchangeJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_removeExchange;
    private javax.swing.JButton btn_robot;
    private javax.swing.JSpinner delay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_linhas;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTextField txt_desc;
    private javax.swing.JTextField txt_prov;
    // End of variables declaration//GEN-END:variables

    private void preencherTabela() {
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        tb.setRowCount(0);
        String filter1 = txt_desc.getText().toUpperCase(),
                filter2 = txt_prov.getText().toUpperCase();
        double total = 0;

        for (Product p : products_exchange) {
            if (filter1.equals("") && filter2.equals("")) {
                tb.addRow(new Object[]{p.getCode(), p.getDescription(), p.getProvider(), p.getAmount()});
                total += p.getAmount();
            } else if (p.getDescription().toUpperCase().contains(filter1) && p.getProvider().toUpperCase().contains(filter2)) {
                tb.addRow(new Object[]{p.getCode(), p.getDescription(), p.getProvider(), p.getAmount()});
                total += p.getAmount();
            }
        }
        lbl_linhas.setText("Linhas: " + jTable1.getRowCount());
        lbl_total.setText("Total: " + CDbl.CDblDuasCasasString(total));
        btn_removeExchange.setEnabled(false);
    }

    private String getCodeSelected(int x) {
        return (String) jTable1.getValueAt(x, 0);
    }

    private String getAmountSelected(int x, String un) throws Exception {
        int local = 3;
        double amount = (double) jTable1.getValueAt(x, local);
        if (un.equals("UN")) {
            // pode retornar valor 0
            return Integer.toString((int) amount);
        }
        return Double.toString(CDbl.CDblDuasCasas(amount));
    }

}
